// emojiColorMap.ts
export const emojiColorMap: Record<string, string> = {
    "🔥": "border-orange-500",
    "❤️": "border-red-500",
    "🧠": "border-pink-500",
    "✍️": "border-yellow-500",
    "🎭": "border-blue-500",
    "🌌": "border-indigo-500",
    "💻": "border-gray-500",
    "⚖️": "border-neutral-500",
    "📚": "border-amber-500",
    "🔍": "border-teal-500",
    "📖": "border-sky-500",
    "💡": "border-lime-500",
    "🎨": "border-rose-500",
    "🧬": "border-cyan-500",
    "👥": "border-violet-500",
    "📈": "border-green-500",
    "🗺️": "border-blue-300",
    "🧱": "border-stone-500",
    "🕰️": "border-amber-700",
    "🎯": "border-emerald-500",
    "🚀": "border-fuchsia-500",
    "🛠️": "border-gray-600",
    "💬": "border-blue-400",
    "🌱": "border-green-400",
    "🏛️": "border-yellow-600",
    "📸": "border-orange-400",
    "🔮": "border-purple-400",
    "🎵": "border-indigo-400",
    "🏞️": "border-green-600",
    "📊": "border-blue-600",
    "📌": "border-red-400",
    "📦": "border-stone-400",
    "🔗": "border-zinc-500",
    "🧭": "border-cyan-400",
    "🏗️": "border-yellow-700",
    "🌉": "border-sky-600",
    "🎓": "border-emerald-700",
    "💭": "border-slate-300",
    "📂": "border-gray-400",
    "🧾": "border-zinc-300",
    "📅": "border-blue-200",
    "⚡": "border-yellow-400",
    "🎁": "border-pink-400",
    "🗃️": "border-slate-500",
    "📽️": "border-red-600",
    "🧸": "border-amber-300",
    "🧵": "border-rose-300",
    "🖼️": "border-indigo-300",
    "📎": "border-slate-400",
    "🎙️": "border-purple-500",
    "📐": "border-lime-400",
    "💼": "border-zinc-700"
  };
  